import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Layout from './components/Layout'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="main">
            <div className="gradient" />
          </div>
          <div className="app font-inter">
            <Layout>
              <Header />
              {children}
            </Layout>
          </div>
        </main>
      </body>
    </html>
  </>
}
